/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Study from './Study';





/**
* The GetStudiesResponse model module.
* @module model/GetStudiesResponse
* @version 2.0
*/
export default class GetStudiesResponse {
    /**
    * Constructs a new <code>GetStudiesResponse</code>.
    * @alias module:model/GetStudiesResponse
    * @class
    * @param description {String} Can be used as body of help info popup
    * @param summary {String} Can be used as title in help info popup
    */

    constructor(description, summary) {
        

        
        

        this['description'] = description;this['summary'] = summary;

        
    }

    /**
    * Constructs a <code>GetStudiesResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GetStudiesResponse} obj Optional instance to populate.
    * @return {module:model/GetStudiesResponse} The populated <code>GetStudiesResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetStudiesResponse();

            
            
            

            if (data.hasOwnProperty('studies')) {
                obj['studies'] = ApiClient.convertToType(data['studies'], [Study]);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/Study>} studies
    */
    studies = undefined;
    /**
    * Can be used as body of help info popup
    * @member {String} description
    */
    description = undefined;
    /**
    * Can be used as title in help info popup
    * @member {String} summary
    */
    summary = undefined;








}


