/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PostCorrelation model module.
* @module model/PostCorrelation
* @version 2.0
*/
export default class PostCorrelation {
    /**
    * Constructs a new <code>PostCorrelation</code>.
    * @alias module:model/PostCorrelation
    * @class
    * @param causeVariableName {String} Cause variable name
    * @param correlation {Number} Correlation value
    * @param effectVariableName {String} Effect variable name
    */

    constructor(causeVariableName, correlation, effectVariableName) {
        

        
        

        this['causeVariableName'] = causeVariableName;this['correlation'] = correlation;this['effectVariableName'] = effectVariableName;

        
    }

    /**
    * Constructs a <code>PostCorrelation</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PostCorrelation} obj Optional instance to populate.
    * @return {module:model/PostCorrelation} The populated <code>PostCorrelation</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostCorrelation();

            
            
            

            if (data.hasOwnProperty('causeVariableName')) {
                obj['causeVariableName'] = ApiClient.convertToType(data['causeVariableName'], 'String');
            }
            if (data.hasOwnProperty('correlation')) {
                obj['correlation'] = ApiClient.convertToType(data['correlation'], 'Number');
            }
            if (data.hasOwnProperty('effectVariableName')) {
                obj['effectVariableName'] = ApiClient.convertToType(data['effectVariableName'], 'String');
            }
            if (data.hasOwnProperty('vote')) {
                obj['vote'] = ApiClient.convertToType(data['vote'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Cause variable name
    * @member {String} causeVariableName
    */
    causeVariableName = undefined;
    /**
    * Correlation value
    * @member {Number} correlation
    */
    correlation = undefined;
    /**
    * Effect variable name
    * @member {String} effectVariableName
    */
    effectVariableName = undefined;
    /**
    * Vote: 0 or 1
    * @member {Number} vote
    */
    vote = undefined;








}


