/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The StudyLinks model module.
* @module model/StudyLinks
* @version 2.0
*/
export default class StudyLinks {
    /**
    * Constructs a new <code>StudyLinks</code>.
    * @alias module:model/StudyLinks
    * @class
    * @param studyLinkEmail {String} Ex: mailto:?subject=N1%20Study%3A%20Sleep%20Quality%20Predicts%20Higher%20Overall%20Mood&body=Check%20out%20my%20study%20at%20https%3A%2F%2Flocal.quantimo.do%2Fapi%2Fv2%2Fstudy%3FcauseVariableName%3DSleep%2520Quality%26effectVariableName%3DOverall%2520Mood%26userId%3D230%0A%0AHave%20a%20great%20day!
    * @param studyLinkFacebook {String} Ex: https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Flocal.quantimo.do%2Fapi%2Fv2%2Fstudy%3FcauseVariableName%3DSleep%2520Quality%26effectVariableName%3DOverall%2520Mood%26userId%3D230
    * @param studyLinkGoogle {String} Ex: https://plus.google.com/share?url=https%3A%2F%2Flocal.quantimo.do%2Fapi%2Fv2%2Fstudy%3FcauseVariableName%3DSleep%2520Quality%26effectVariableName%3DOverall%2520Mood%26userId%3D230
    * @param studyLinkStatic {String} Ex: https://local.quantimo.do/api/v2/study?causeVariableName=Sleep%20Quality&effectVariableName=Overall%20Mood&userId=230
    * @param studyLinkDynamic {String} Ex: https://local.quantimo.do/ionic/Modo/www/index.html#/app/study?causeVariableName=Sleep%20Quality&effectVariableName=Overall%20Mood&userId=230
    * @param studyLinkTwitter {String} Ex: https://twitter.com/home?status=Sleep%20Quality%20Predicts%20Higher%20Overall%20Mood%20https%3A%2F%2Flocal.quantimo.do%2Fapi%2Fv2%2Fstudy%3FcauseVariableName%3DSleep%2520Quality%26effectVariableName%3DOverall%2520Mood%26userId%3D230%20%40quantimodo
    */

    constructor(studyLinkEmail, studyLinkFacebook, studyLinkGoogle, studyLinkStatic, studyLinkDynamic, studyLinkTwitter) {
        

        
        

        this['studyLinkEmail'] = studyLinkEmail;this['studyLinkFacebook'] = studyLinkFacebook;this['studyLinkGoogle'] = studyLinkGoogle;this['studyLinkStatic'] = studyLinkStatic;this['studyLinkDynamic'] = studyLinkDynamic;this['studyLinkTwitter'] = studyLinkTwitter;

        
    }

    /**
    * Constructs a <code>StudyLinks</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/StudyLinks} obj Optional instance to populate.
    * @return {module:model/StudyLinks} The populated <code>StudyLinks</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StudyLinks();

            
            
            

            if (data.hasOwnProperty('studyLinkEmail')) {
                obj['studyLinkEmail'] = ApiClient.convertToType(data['studyLinkEmail'], 'String');
            }
            if (data.hasOwnProperty('studyLinkFacebook')) {
                obj['studyLinkFacebook'] = ApiClient.convertToType(data['studyLinkFacebook'], 'String');
            }
            if (data.hasOwnProperty('studyLinkGoogle')) {
                obj['studyLinkGoogle'] = ApiClient.convertToType(data['studyLinkGoogle'], 'String');
            }
            if (data.hasOwnProperty('studyLinkStatic')) {
                obj['studyLinkStatic'] = ApiClient.convertToType(data['studyLinkStatic'], 'String');
            }
            if (data.hasOwnProperty('studyLinkDynamic')) {
                obj['studyLinkDynamic'] = ApiClient.convertToType(data['studyLinkDynamic'], 'String');
            }
            if (data.hasOwnProperty('studyLinkTwitter')) {
                obj['studyLinkTwitter'] = ApiClient.convertToType(data['studyLinkTwitter'], 'String');
            }
        }
        return obj;
    }

    /**
    * Ex: mailto:?subject=N1%20Study%3A%20Sleep%20Quality%20Predicts%20Higher%20Overall%20Mood&body=Check%20out%20my%20study%20at%20https%3A%2F%2Flocal.quantimo.do%2Fapi%2Fv2%2Fstudy%3FcauseVariableName%3DSleep%2520Quality%26effectVariableName%3DOverall%2520Mood%26userId%3D230%0A%0AHave%20a%20great%20day!
    * @member {String} studyLinkEmail
    */
    studyLinkEmail = undefined;
    /**
    * Ex: https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Flocal.quantimo.do%2Fapi%2Fv2%2Fstudy%3FcauseVariableName%3DSleep%2520Quality%26effectVariableName%3DOverall%2520Mood%26userId%3D230
    * @member {String} studyLinkFacebook
    */
    studyLinkFacebook = undefined;
    /**
    * Ex: https://plus.google.com/share?url=https%3A%2F%2Flocal.quantimo.do%2Fapi%2Fv2%2Fstudy%3FcauseVariableName%3DSleep%2520Quality%26effectVariableName%3DOverall%2520Mood%26userId%3D230
    * @member {String} studyLinkGoogle
    */
    studyLinkGoogle = undefined;
    /**
    * Ex: https://local.quantimo.do/api/v2/study?causeVariableName=Sleep%20Quality&effectVariableName=Overall%20Mood&userId=230
    * @member {String} studyLinkStatic
    */
    studyLinkStatic = undefined;
    /**
    * Ex: https://local.quantimo.do/ionic/Modo/www/index.html#/app/study?causeVariableName=Sleep%20Quality&effectVariableName=Overall%20Mood&userId=230
    * @member {String} studyLinkDynamic
    */
    studyLinkDynamic = undefined;
    /**
    * Ex: https://twitter.com/home?status=Sleep%20Quality%20Predicts%20Higher%20Overall%20Mood%20https%3A%2F%2Flocal.quantimo.do%2Fapi%2Fv2%2Fstudy%3FcauseVariableName%3DSleep%2520Quality%26effectVariableName%3DOverall%2520Mood%26userId%3D230%20%40quantimodo
    * @member {String} studyLinkTwitter
    */
    studyLinkTwitter = undefined;








}


