/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The TrackingReminderNotificationTrackAllAction model module.
* @module model/TrackingReminderNotificationTrackAllAction
* @version 2.0
*/
export default class TrackingReminderNotificationTrackAllAction {
    /**
    * Constructs a new <code>TrackingReminderNotificationTrackAllAction</code>.
    * @alias module:model/TrackingReminderNotificationTrackAllAction
    * @class
    * @param action {String} Ex: trackAll
    * @param callback {String} Ex: trackThreeRatingAction
    * @param modifiedValue {Number} Ex: 3
    * @param title {String} Ex: Rate 3/5 for all
    */

    constructor(action, callback, modifiedValue, title) {
        

        
        

        this['action'] = action;this['callback'] = callback;this['modifiedValue'] = modifiedValue;this['title'] = title;

        
    }

    /**
    * Constructs a <code>TrackingReminderNotificationTrackAllAction</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TrackingReminderNotificationTrackAllAction} obj Optional instance to populate.
    * @return {module:model/TrackingReminderNotificationTrackAllAction} The populated <code>TrackingReminderNotificationTrackAllAction</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrackingReminderNotificationTrackAllAction();

            
            
            

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('callback')) {
                obj['callback'] = ApiClient.convertToType(data['callback'], 'String');
            }
            if (data.hasOwnProperty('modifiedValue')) {
                obj['modifiedValue'] = ApiClient.convertToType(data['modifiedValue'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }

    /**
    * Ex: trackAll
    * @member {String} action
    */
    action = undefined;
    /**
    * Ex: trackThreeRatingAction
    * @member {String} callback
    */
    callback = undefined;
    /**
    * Ex: 3
    * @member {Number} modifiedValue
    */
    modifiedValue = undefined;
    /**
    * Ex: Rate 3/5 for all
    * @member {String} title
    */
    title = undefined;








}


