/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import DataSource from './DataSource';
import TrackingReminderNotificationAction from './TrackingReminderNotificationAction';
import Unit from './Unit';
import Variable from './Variable';
import VariableCategory from './VariableCategory';
import VariableCharts from './VariableCharts';





/**
* The Variable model module.
* @module model/Variable
* @version 2.0
*/
export default class Variable {
    /**
    * Constructs a new <code>Variable</code>.
    * @alias module:model/Variable
    * @class
    * @param id {Number} Ex: 95614
    * @param name {String} Ex: Trader Joes Bedtime Tea / Sleepytime Tea (any Brand)
    * @param userId {Number} User ID
    * @param variableId {Number} Ex: 96380
    */

    constructor(id, name, userId, variableId) {
        

        
        

        this['id'] = id;this['name'] = name;this['userId'] = userId;this['variableId'] = variableId;

        
    }

    /**
    * Constructs a <code>Variable</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Variable} obj Optional instance to populate.
    * @return {module:model/Variable} The populated <code>Variable</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Variable();

            
            
            

            if (data.hasOwnProperty('actionArray')) {
                obj['actionArray'] = ApiClient.convertToType(data['actionArray'], [TrackingReminderNotificationAction]);
            }
            if (data.hasOwnProperty('alias')) {
                obj['alias'] = ApiClient.convertToType(data['alias'], 'String');
            }
            if (data.hasOwnProperty('availableUnits')) {
                obj['availableUnits'] = ApiClient.convertToType(data['availableUnits'], [Unit]);
            }
            if (data.hasOwnProperty('causeOnly')) {
                obj['causeOnly'] = ApiClient.convertToType(data['causeOnly'], 'Boolean');
            }
            if (data.hasOwnProperty('charts')) {
                obj['charts'] = VariableCharts.constructFromObject(data['charts']);
            }
            if (data.hasOwnProperty('chartsLinkDynamic')) {
                obj['chartsLinkDynamic'] = ApiClient.convertToType(data['chartsLinkDynamic'], 'String');
            }
            if (data.hasOwnProperty('chartsLinkEmail')) {
                obj['chartsLinkEmail'] = ApiClient.convertToType(data['chartsLinkEmail'], 'String');
            }
            if (data.hasOwnProperty('chartsLinkFacebook')) {
                obj['chartsLinkFacebook'] = ApiClient.convertToType(data['chartsLinkFacebook'], 'String');
            }
            if (data.hasOwnProperty('chartsLinkGoogle')) {
                obj['chartsLinkGoogle'] = ApiClient.convertToType(data['chartsLinkGoogle'], 'String');
            }
            if (data.hasOwnProperty('chartsLinkStatic')) {
                obj['chartsLinkStatic'] = ApiClient.convertToType(data['chartsLinkStatic'], 'String');
            }
            if (data.hasOwnProperty('chartsLinkTwitter')) {
                obj['chartsLinkTwitter'] = ApiClient.convertToType(data['chartsLinkTwitter'], 'String');
            }
            if (data.hasOwnProperty('childCommonTagVariables')) {
                obj['childCommonTagVariables'] = ApiClient.convertToType(data['childCommonTagVariables'], [Variable]);
            }
            if (data.hasOwnProperty('childUserTagVariables')) {
                obj['childUserTagVariables'] = ApiClient.convertToType(data['childUserTagVariables'], [Variable]);
            }
            if (data.hasOwnProperty('clientId')) {
                obj['clientId'] = ApiClient.convertToType(data['clientId'], 'String');
            }
            if (data.hasOwnProperty('combinationOperation')) {
                obj['combinationOperation'] = ApiClient.convertToType(data['combinationOperation'], 'String');
            }
            if (data.hasOwnProperty('commonAlias')) {
                obj['commonAlias'] = ApiClient.convertToType(data['commonAlias'], 'String');
            }
            if (data.hasOwnProperty('commonTaggedVariables')) {
                obj['commonTaggedVariables'] = ApiClient.convertToType(data['commonTaggedVariables'], [Variable]);
            }
            if (data.hasOwnProperty('commonTagVariables')) {
                obj['commonTagVariables'] = ApiClient.convertToType(data['commonTagVariables'], [Variable]);
            }
            if (data.hasOwnProperty('commonVariableMostCommonConnectorId')) {
                obj['commonVariableMostCommonConnectorId'] = ApiClient.convertToType(data['commonVariableMostCommonConnectorId'], 'Number');
            }
            if (data.hasOwnProperty('commonVariableUpdatedAt')) {
                obj['commonVariableUpdatedAt'] = ApiClient.convertToType(data['commonVariableUpdatedAt'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('unitAbbreviatedName')) {
                obj['unitAbbreviatedName'] = ApiClient.convertToType(data['unitAbbreviatedName'], 'String');
            }
            if (data.hasOwnProperty('unitCategoryId')) {
                obj['unitCategoryId'] = ApiClient.convertToType(data['unitCategoryId'], 'Number');
            }
            if (data.hasOwnProperty('unitCategoryName')) {
                obj['unitCategoryName'] = ApiClient.convertToType(data['unitCategoryName'], 'String');
            }
            if (data.hasOwnProperty('unitId')) {
                obj['unitId'] = ApiClient.convertToType(data['unitId'], 'Number');
            }
            if (data.hasOwnProperty('unitName')) {
                obj['unitName'] = ApiClient.convertToType(data['unitName'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('durationOfAction')) {
                obj['durationOfAction'] = ApiClient.convertToType(data['durationOfAction'], 'Number');
            }
            if (data.hasOwnProperty('durationOfActionInHours')) {
                obj['durationOfActionInHours'] = ApiClient.convertToType(data['durationOfActionInHours'], 'Number');
            }
            if (data.hasOwnProperty('earliestFillingTime')) {
                obj['earliestFillingTime'] = ApiClient.convertToType(data['earliestFillingTime'], 'Number');
            }
            if (data.hasOwnProperty('earliestMeasurementTime')) {
                obj['earliestMeasurementTime'] = ApiClient.convertToType(data['earliestMeasurementTime'], 'Number');
            }
            if (data.hasOwnProperty('earliestSourceTime')) {
                obj['earliestSourceTime'] = ApiClient.convertToType(data['earliestSourceTime'], 'Number');
            }
            if (data.hasOwnProperty('errorMessage')) {
                obj['errorMessage'] = ApiClient.convertToType(data['errorMessage'], 'String');
            }
            if (data.hasOwnProperty('experimentEndTime')) {
                obj['experimentEndTime'] = ApiClient.convertToType(data['experimentEndTime'], 'String');
            }
            if (data.hasOwnProperty('experimentEndTimeSeconds')) {
                obj['experimentEndTimeSeconds'] = ApiClient.convertToType(data['experimentEndTimeSeconds'], 'Number');
            }
            if (data.hasOwnProperty('experimentEndTimeString')) {
                obj['experimentEndTimeString'] = ApiClient.convertToType(data['experimentEndTimeString'], 'String');
            }
            if (data.hasOwnProperty('experimentStartTime')) {
                obj['experimentStartTime'] = ApiClient.convertToType(data['experimentStartTime'], 'String');
            }
            if (data.hasOwnProperty('experimentStartTimeSeconds')) {
                obj['experimentStartTimeSeconds'] = ApiClient.convertToType(data['experimentStartTimeSeconds'], 'Number');
            }
            if (data.hasOwnProperty('experimentStartTimeString')) {
                obj['experimentStartTimeString'] = ApiClient.convertToType(data['experimentStartTimeString'], 'String');
            }
            if (data.hasOwnProperty('fillingType')) {
                obj['fillingType'] = ApiClient.convertToType(data['fillingType'], 'String');
            }
            if (data.hasOwnProperty('fillingValue')) {
                obj['fillingValue'] = ApiClient.convertToType(data['fillingValue'], 'Number');
            }
            if (data.hasOwnProperty('iconIcon')) {
                obj['iconIcon'] = ApiClient.convertToType(data['iconIcon'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('imageUrl')) {
                obj['imageUrl'] = ApiClient.convertToType(data['imageUrl'], 'String');
            }
            if (data.hasOwnProperty('informationalUrl')) {
                obj['informationalUrl'] = ApiClient.convertToType(data['informationalUrl'], 'String');
            }
            if (data.hasOwnProperty('ingredientOfCommonTagVariables')) {
                obj['ingredientOfCommonTagVariables'] = ApiClient.convertToType(data['ingredientOfCommonTagVariables'], [Variable]);
            }
            if (data.hasOwnProperty('ingredientCommonTagVariables')) {
                obj['ingredientCommonTagVariables'] = ApiClient.convertToType(data['ingredientCommonTagVariables'], [Variable]);
            }
            if (data.hasOwnProperty('ingredientOfUserTagVariables')) {
                obj['ingredientOfUserTagVariables'] = ApiClient.convertToType(data['ingredientOfUserTagVariables'], [Variable]);
            }
            if (data.hasOwnProperty('ingredientUserTagVariables')) {
                obj['ingredientUserTagVariables'] = ApiClient.convertToType(data['ingredientUserTagVariables'], [Variable]);
            }
            if (data.hasOwnProperty('inputType')) {
                obj['inputType'] = ApiClient.convertToType(data['inputType'], 'String');
            }
            if (data.hasOwnProperty('ionIcon')) {
                obj['ionIcon'] = ApiClient.convertToType(data['ionIcon'], 'String');
            }
            if (data.hasOwnProperty('joinedCommonTagVariables')) {
                obj['joinedCommonTagVariables'] = ApiClient.convertToType(data['joinedCommonTagVariables'], [Variable]);
            }
            if (data.hasOwnProperty('joinedUserTagVariables')) {
                obj['joinedUserTagVariables'] = ApiClient.convertToType(data['joinedUserTagVariables'], [Variable]);
            }
            if (data.hasOwnProperty('joinWith')) {
                obj['joinWith'] = ApiClient.convertToType(data['joinWith'], 'Number');
            }
            if (data.hasOwnProperty('kurtosis')) {
                obj['kurtosis'] = ApiClient.convertToType(data['kurtosis'], 'Number');
            }
            if (data.hasOwnProperty('lastOriginalUnitId')) {
                obj['lastOriginalUnitId'] = ApiClient.convertToType(data['lastOriginalUnitId'], 'Number');
            }
            if (data.hasOwnProperty('lastOriginalValue')) {
                obj['lastOriginalValue'] = ApiClient.convertToType(data['lastOriginalValue'], 'Number');
            }
            if (data.hasOwnProperty('lastProcessedDailyValue')) {
                obj['lastProcessedDailyValue'] = ApiClient.convertToType(data['lastProcessedDailyValue'], 'Number');
            }
            if (data.hasOwnProperty('lastSuccessfulUpdateTime')) {
                obj['lastSuccessfulUpdateTime'] = ApiClient.convertToType(data['lastSuccessfulUpdateTime'], 'String');
            }
            if (data.hasOwnProperty('lastUnitId')) {
                obj['lastUnitId'] = ApiClient.convertToType(data['lastUnitId'], 'Number');
            }
            if (data.hasOwnProperty('lastValue')) {
                obj['lastValue'] = ApiClient.convertToType(data['lastValue'], 'Number');
            }
            if (data.hasOwnProperty('latestFillingTime')) {
                obj['latestFillingTime'] = ApiClient.convertToType(data['latestFillingTime'], 'Number');
            }
            if (data.hasOwnProperty('latestMeasurementTime')) {
                obj['latestMeasurementTime'] = ApiClient.convertToType(data['latestMeasurementTime'], 'Number');
            }
            if (data.hasOwnProperty('latestSourceTime')) {
                obj['latestSourceTime'] = ApiClient.convertToType(data['latestSourceTime'], 'Number');
            }
            if (data.hasOwnProperty('latestUserMeasurementTime')) {
                obj['latestUserMeasurementTime'] = ApiClient.convertToType(data['latestUserMeasurementTime'], 'Number');
            }
            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
            }
            if (data.hasOwnProperty('manualTracking')) {
                obj['manualTracking'] = ApiClient.convertToType(data['manualTracking'], 'Boolean');
            }
            if (data.hasOwnProperty('maximumAllowedValue')) {
                obj['maximumAllowedValue'] = ApiClient.convertToType(data['maximumAllowedValue'], 'Number');
            }
            if (data.hasOwnProperty('maximumRecordedDailyValue')) {
                obj['maximumRecordedDailyValue'] = ApiClient.convertToType(data['maximumRecordedDailyValue'], 'Number');
            }
            if (data.hasOwnProperty('maximumRecordedValue')) {
                obj['maximumRecordedValue'] = ApiClient.convertToType(data['maximumRecordedValue'], 'Number');
            }
            if (data.hasOwnProperty('mean')) {
                obj['mean'] = ApiClient.convertToType(data['mean'], 'Number');
            }
            if (data.hasOwnProperty('measurementsAtLastAnalysis')) {
                obj['measurementsAtLastAnalysis'] = ApiClient.convertToType(data['measurementsAtLastAnalysis'], 'Number');
            }
            if (data.hasOwnProperty('median')) {
                obj['median'] = ApiClient.convertToType(data['median'], 'Number');
            }
            if (data.hasOwnProperty('minimumAllowedValue')) {
                obj['minimumAllowedValue'] = ApiClient.convertToType(data['minimumAllowedValue'], 'Number');
            }
            if (data.hasOwnProperty('minimumRecordedValue')) {
                obj['minimumRecordedValue'] = ApiClient.convertToType(data['minimumRecordedValue'], 'Number');
            }
            if (data.hasOwnProperty('mostCommonConnectorId')) {
                obj['mostCommonConnectorId'] = ApiClient.convertToType(data['mostCommonConnectorId'], 'Number');
            }
            if (data.hasOwnProperty('mostCommonOriginalUnitId')) {
                obj['mostCommonOriginalUnitId'] = ApiClient.convertToType(data['mostCommonOriginalUnitId'], 'Number');
            }
            if (data.hasOwnProperty('mostCommonUnitId')) {
                obj['mostCommonUnitId'] = ApiClient.convertToType(data['mostCommonUnitId'], 'Number');
            }
            if (data.hasOwnProperty('mostCommonValue')) {
                obj['mostCommonValue'] = ApiClient.convertToType(data['mostCommonValue'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('numberOfAggregateCorrelationsAsCause')) {
                obj['numberOfAggregateCorrelationsAsCause'] = ApiClient.convertToType(data['numberOfAggregateCorrelationsAsCause'], 'Number');
            }
            if (data.hasOwnProperty('numberOfAggregateCorrelationsAsEffect')) {
                obj['numberOfAggregateCorrelationsAsEffect'] = ApiClient.convertToType(data['numberOfAggregateCorrelationsAsEffect'], 'Number');
            }
            if (data.hasOwnProperty('numberOfChanges')) {
                obj['numberOfChanges'] = ApiClient.convertToType(data['numberOfChanges'], 'Number');
            }
            if (data.hasOwnProperty('numberOfCorrelations')) {
                obj['numberOfCorrelations'] = ApiClient.convertToType(data['numberOfCorrelations'], 'Number');
            }
            if (data.hasOwnProperty('numberOfProcessedDailyMeasurements')) {
                obj['numberOfProcessedDailyMeasurements'] = ApiClient.convertToType(data['numberOfProcessedDailyMeasurements'], 'Number');
            }
            if (data.hasOwnProperty('numberOfRawMeasurements')) {
                obj['numberOfRawMeasurements'] = ApiClient.convertToType(data['numberOfRawMeasurements'], 'Number');
            }
            if (data.hasOwnProperty('numberOfTrackingReminders')) {
                obj['numberOfTrackingReminders'] = ApiClient.convertToType(data['numberOfTrackingReminders'], 'Number');
            }
            if (data.hasOwnProperty('numberOfUniqueDailyValues')) {
                obj['numberOfUniqueDailyValues'] = ApiClient.convertToType(data['numberOfUniqueDailyValues'], 'Number');
            }
            if (data.hasOwnProperty('numberOfUniqueValues')) {
                obj['numberOfUniqueValues'] = ApiClient.convertToType(data['numberOfUniqueValues'], 'Number');
            }
            if (data.hasOwnProperty('numberOfUserCorrelationsAsCause')) {
                obj['numberOfUserCorrelationsAsCause'] = ApiClient.convertToType(data['numberOfUserCorrelationsAsCause'], 'Number');
            }
            if (data.hasOwnProperty('numberOfUserCorrelationsAsEffect')) {
                obj['numberOfUserCorrelationsAsEffect'] = ApiClient.convertToType(data['numberOfUserCorrelationsAsEffect'], 'Number');
            }
            if (data.hasOwnProperty('numberOfUserVariables')) {
                obj['numberOfUserVariables'] = ApiClient.convertToType(data['numberOfUserVariables'], 'Number');
            }
            if (data.hasOwnProperty('onsetDelay')) {
                obj['onsetDelay'] = ApiClient.convertToType(data['onsetDelay'], 'Number');
            }
            if (data.hasOwnProperty('onsetDelayInHours')) {
                obj['onsetDelayInHours'] = ApiClient.convertToType(data['onsetDelayInHours'], 'Number');
            }
            if (data.hasOwnProperty('outcome')) {
                obj['outcome'] = ApiClient.convertToType(data['outcome'], 'Boolean');
            }
            if (data.hasOwnProperty('outcomeOfInterest')) {
                obj['outcomeOfInterest'] = ApiClient.convertToType(data['outcomeOfInterest'], 'Number');
            }
            if (data.hasOwnProperty('parentCommonTagVariables')) {
                obj['parentCommonTagVariables'] = ApiClient.convertToType(data['parentCommonTagVariables'], [Variable]);
            }
            if (data.hasOwnProperty('parentUserTagVariables')) {
                obj['parentUserTagVariables'] = ApiClient.convertToType(data['parentUserTagVariables'], [Variable]);
            }
            if (data.hasOwnProperty('pngPath')) {
                obj['pngPath'] = ApiClient.convertToType(data['pngPath'], 'String');
            }
            if (data.hasOwnProperty('pngUrl')) {
                obj['pngUrl'] = ApiClient.convertToType(data['pngUrl'], 'String');
            }
            if (data.hasOwnProperty('predictorOfInterest')) {
                obj['predictorOfInterest'] = ApiClient.convertToType(data['predictorOfInterest'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('productUrl')) {
                obj['productUrl'] = ApiClient.convertToType(data['productUrl'], 'String');
            }
            if (data.hasOwnProperty('public')) {
                obj['public'] = ApiClient.convertToType(data['public'], 'Number');
            }
            if (data.hasOwnProperty('rawMeasurementsAtLastAnalysis')) {
                obj['rawMeasurementsAtLastAnalysis'] = ApiClient.convertToType(data['rawMeasurementsAtLastAnalysis'], 'Number');
            }
            if (data.hasOwnProperty('secondMostCommonValue')) {
                obj['secondMostCommonValue'] = ApiClient.convertToType(data['secondMostCommonValue'], 'Number');
            }
            if (data.hasOwnProperty('secondToLastValue')) {
                obj['secondToLastValue'] = ApiClient.convertToType(data['secondToLastValue'], 'Number');
            }
            if (data.hasOwnProperty('shareUserMeasurements')) {
                obj['shareUserMeasurements'] = ApiClient.convertToType(data['shareUserMeasurements'], 'Boolean');
            }
            if (data.hasOwnProperty('skewness')) {
                obj['skewness'] = ApiClient.convertToType(data['skewness'], 'Number');
            }
            if (data.hasOwnProperty('sources')) {
                obj['sources'] = ApiClient.convertToType(data['sources'], 'String');
            }
            if (data.hasOwnProperty('standardDeviation')) {
                obj['standardDeviation'] = ApiClient.convertToType(data['standardDeviation'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('subtitle')) {
                obj['subtitle'] = ApiClient.convertToType(data['subtitle'], 'String');
            }
            if (data.hasOwnProperty('svgUrl')) {
                obj['svgUrl'] = ApiClient.convertToType(data['svgUrl'], 'String');
            }
            if (data.hasOwnProperty('thirdMostCommonValue')) {
                obj['thirdMostCommonValue'] = ApiClient.convertToType(data['thirdMostCommonValue'], 'Number');
            }
            if (data.hasOwnProperty('thirdToLastValue')) {
                obj['thirdToLastValue'] = ApiClient.convertToType(data['thirdToLastValue'], 'Number');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = Unit.constructFromObject(data['unit']);
            }
            if (data.hasOwnProperty('upc')) {
                obj['upc'] = ApiClient.convertToType(data['upc'], 'String');
            }
            if (data.hasOwnProperty('updated')) {
                obj['updated'] = ApiClient.convertToType(data['updated'], 'Number');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'String');
            }
            if (data.hasOwnProperty('updatedTime')) {
                obj['updatedTime'] = ApiClient.convertToType(data['updatedTime'], 'String');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
            if (data.hasOwnProperty('userTaggedVariables')) {
                obj['userTaggedVariables'] = ApiClient.convertToType(data['userTaggedVariables'], [Variable]);
            }
            if (data.hasOwnProperty('userTagVariables')) {
                obj['userTagVariables'] = ApiClient.convertToType(data['userTagVariables'], [Variable]);
            }
            if (data.hasOwnProperty('userVariableUnitAbbreviatedName')) {
                obj['userVariableUnitAbbreviatedName'] = ApiClient.convertToType(data['userVariableUnitAbbreviatedName'], 'String');
            }
            if (data.hasOwnProperty('userVariableUnitCategoryId')) {
                obj['userVariableUnitCategoryId'] = ApiClient.convertToType(data['userVariableUnitCategoryId'], 'Number');
            }
            if (data.hasOwnProperty('userVariableUnitCategoryName')) {
                obj['userVariableUnitCategoryName'] = ApiClient.convertToType(data['userVariableUnitCategoryName'], 'String');
            }
            if (data.hasOwnProperty('userVariableUnitId')) {
                obj['userVariableUnitId'] = ApiClient.convertToType(data['userVariableUnitId'], 'Number');
            }
            if (data.hasOwnProperty('userVariableUnitName')) {
                obj['userVariableUnitName'] = ApiClient.convertToType(data['userVariableUnitName'], 'String');
            }
            if (data.hasOwnProperty('userVariableFillingValue')) {
                obj['userVariableFillingValue'] = ApiClient.convertToType(data['userVariableFillingValue'], 'Number');
            }
            if (data.hasOwnProperty('userVariableMostCommonConnectorId')) {
                obj['userVariableMostCommonConnectorId'] = ApiClient.convertToType(data['userVariableMostCommonConnectorId'], 'Number');
            }
            if (data.hasOwnProperty('userVariableUpdatedAt')) {
                obj['userVariableUpdatedAt'] = ApiClient.convertToType(data['userVariableUpdatedAt'], 'String');
            }
            if (data.hasOwnProperty('userVariableValence')) {
                obj['userVariableValence'] = ApiClient.convertToType(data['userVariableValence'], 'String');
            }
            if (data.hasOwnProperty('userVariableVariableCategoryId')) {
                obj['userVariableVariableCategoryId'] = ApiClient.convertToType(data['userVariableVariableCategoryId'], 'Number');
            }
            if (data.hasOwnProperty('userVariableVariableCategoryName')) {
                obj['userVariableVariableCategoryName'] = ApiClient.convertToType(data['userVariableVariableCategoryName'], 'String');
            }
            if (data.hasOwnProperty('userVariableWikipediaTitle')) {
                obj['userVariableWikipediaTitle'] = ApiClient.convertToType(data['userVariableWikipediaTitle'], 'String');
            }
            if (data.hasOwnProperty('variableCategory')) {
                obj['variableCategory'] = VariableCategory.constructFromObject(data['variableCategory']);
            }
            if (data.hasOwnProperty('dataSource')) {
                obj['dataSource'] = DataSource.constructFromObject(data['dataSource']);
            }
            if (data.hasOwnProperty('joinedVariables')) {
                obj['joinedVariables'] = ApiClient.convertToType(data['joinedVariables'], [Variable]);
            }
            if (data.hasOwnProperty('lastSource')) {
                obj['lastSource'] = ApiClient.convertToType(data['lastSource'], 'Number');
            }
            if (data.hasOwnProperty('lastUnit')) {
                obj['lastUnit'] = ApiClient.convertToType(data['lastUnit'], 'String');
            }
            if (data.hasOwnProperty('mostCommonUnit')) {
                obj['mostCommonUnit'] = ApiClient.convertToType(data['mostCommonUnit'], 'String');
            }
            if (data.hasOwnProperty('valence')) {
                obj['valence'] = ApiClient.convertToType(data['valence'], 'String');
            }
            if (data.hasOwnProperty('variableCategoryId')) {
                obj['variableCategoryId'] = ApiClient.convertToType(data['variableCategoryId'], 'Number');
            }
            if (data.hasOwnProperty('variableCategoryImageUrl')) {
                obj['variableCategoryImageUrl'] = ApiClient.convertToType(data['variableCategoryImageUrl'], 'String');
            }
            if (data.hasOwnProperty('variableCategoryName')) {
                obj['variableCategoryName'] = ApiClient.convertToType(data['variableCategoryName'], 'String');
            }
            if (data.hasOwnProperty('variableFillingValue')) {
                obj['variableFillingValue'] = ApiClient.convertToType(data['variableFillingValue'], 'Number');
            }
            if (data.hasOwnProperty('variableId')) {
                obj['variableId'] = ApiClient.convertToType(data['variableId'], 'Number');
            }
            if (data.hasOwnProperty('variableName')) {
                obj['variableName'] = ApiClient.convertToType(data['variableName'], 'String');
            }
            if (data.hasOwnProperty('variance')) {
                obj['variance'] = ApiClient.convertToType(data['variance'], 'Number');
            }
            if (data.hasOwnProperty('wikipediaTitle')) {
                obj['wikipediaTitle'] = ApiClient.convertToType(data['wikipediaTitle'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/TrackingReminderNotificationAction>} actionArray
    */
    actionArray = undefined;
    /**
    * Alternative name
    * @member {String} alias
    */
    alias = undefined;
    /**
    * @member {Array.<module:model/Unit>} availableUnits
    */
    availableUnits = undefined;
    /**
    * A value of 1 indicates that this variable is generally a cause in a causal relationship.  An example of a causeOnly variable would be a variable such as Cloud Cover which would generally not be influenced by the behaviour of the user
    * @member {Boolean} causeOnly
    */
    causeOnly = undefined;
    /**
    * @member {module:model/VariableCharts} charts
    */
    charts = undefined;
    /**
    * Ex: https://local.quantimo.do/ionic/Modo/www/#/app/charts/Trader%20Joes%20Bedtime%20Tea%20%2F%20Sleepytime%20Tea%20%28any%20Brand%29?variableName=Trader%20Joes%20Bedtime%20Tea%20%2F%20Sleepytime%20Tea%20%28any%20Brand%29&userId=230&pngUrl=https%3A%2F%2Fapp.quantimo.do%2Fionic%2FModo%2Fwww%2Fimg%2Fvariable_categories%2Ftreatments.png
    * @member {String} chartsLinkDynamic
    */
    chartsLinkDynamic = undefined;
    /**
    * Ex: mailto:?subject=Check%20out%20my%20Trader%20Joes%20Bedtime%20Tea%20%2F%20Sleepytime%20Tea%20%28any%20Brand%29%20data%21&body=See%20my%20Trader%20Joes%20Bedtime%20Tea%20%2F%20Sleepytime%20Tea%20%28any%20Brand%29%20history%20at%20https%3A%2F%2Flocal.quantimo.do%2Fapi%2Fv2%2Fcharts%3FvariableName%3DTrader%2520Joes%2520Bedtime%2520Tea%2520%252F%2520Sleepytime%2520Tea%2520%2528any%2520Brand%2529%26userId%3D230%26pngUrl%3Dhttps%253A%252F%252Fapp.quantimo.do%252Fionic%252FModo%252Fwww%252Fimg%252Fvariable_categories%252Ftreatments.png%0A%0AHave%20a%20great%20day!
    * @member {String} chartsLinkEmail
    */
    chartsLinkEmail = undefined;
    /**
    * Ex: https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Flocal.quantimo.do%2Fapi%2Fv2%2Fcharts%3FvariableName%3DTrader%2520Joes%2520Bedtime%2520Tea%2520%252F%2520Sleepytime%2520Tea%2520%2528any%2520Brand%2529%26userId%3D230%26pngUrl%3Dhttps%253A%252F%252Fapp.quantimo.do%252Fionic%252FModo%252Fwww%252Fimg%252Fvariable_categories%252Ftreatments.png
    * @member {String} chartsLinkFacebook
    */
    chartsLinkFacebook = undefined;
    /**
    * Ex: https://plus.google.com/share?url=https%3A%2F%2Flocal.quantimo.do%2Fapi%2Fv2%2Fcharts%3FvariableName%3DTrader%2520Joes%2520Bedtime%2520Tea%2520%252F%2520Sleepytime%2520Tea%2520%2528any%2520Brand%2529%26userId%3D230%26pngUrl%3Dhttps%253A%252F%252Fapp.quantimo.do%252Fionic%252FModo%252Fwww%252Fimg%252Fvariable_categories%252Ftreatments.png
    * @member {String} chartsLinkGoogle
    */
    chartsLinkGoogle = undefined;
    /**
    * Ex: https://local.quantimo.do/api/v2/charts?variableName=Trader%20Joes%20Bedtime%20Tea%20%2F%20Sleepytime%20Tea%20%28any%20Brand%29&userId=230&pngUrl=https%3A%2F%2Fapp.quantimo.do%2Fionic%2FModo%2Fwww%2Fimg%2Fvariable_categories%2Ftreatments.png
    * @member {String} chartsLinkStatic
    */
    chartsLinkStatic = undefined;
    /**
    * Ex: https://twitter.com/home?status=Check%20out%20my%20Trader%20Joes%20Bedtime%20Tea%20%2F%20Sleepytime%20Tea%20%28any%20Brand%29%20data%21%20https%3A%2F%2Flocal.quantimo.do%2Fapi%2Fv2%2Fcharts%3FvariableName%3DTrader%2520Joes%2520Bedtime%2520Tea%2520%252F%2520Sleepytime%2520Tea%2520%2528any%2520Brand%2529%26userId%3D230%26pngUrl%3Dhttps%253A%252F%252Fapp.quantimo.do%252Fionic%252FModo%252Fwww%252Fimg%252Fvariable_categories%252Ftreatments.png%20%40quantimodo
    * @member {String} chartsLinkTwitter
    */
    chartsLinkTwitter = undefined;
    /**
    * Commonly defined for all users. An example of a parent category variable would be Fruit when tagged with the child sub-type variables Apple.  Child variable (Apple) measurements will be included when the parent category (Fruit) is analyzed.  This allows us to see how Fruit consumption might be affecting without having to record both Fruit and Apple intake.
    * @member {Array.<module:model/Variable>} childCommonTagVariables
    */
    childCommonTagVariables = undefined;
    /**
    * User-defined. An example of a parent category variable would be Fruit when tagged with the child sub-type variables Apple.  Child variable (Apple) measurements will be included when the parent category (Fruit) is analyzed.  This allows us to see how Fruit consumption might be affecting without having to record both Fruit and Apple intake.
    * @member {Array.<module:model/Variable>} childUserTagVariables
    */
    childUserTagVariables = undefined;
    /**
    * Your QuantiModo client id can be obtained by creating an app at https://builder.quantimo.do
    * @member {String} clientId
    */
    clientId = undefined;
    /**
    * Ex: MEAN
    * @member {String} combinationOperation
    */
    combinationOperation = undefined;
    /**
    * Ex: Anxiety / Nervousness
    * @member {String} commonAlias
    */
    commonAlias = undefined;
    /**
    * @member {Array.<module:model/Variable>} commonTaggedVariables
    */
    commonTaggedVariables = undefined;
    /**
    * @member {Array.<module:model/Variable>} commonTagVariables
    */
    commonTagVariables = undefined;
    /**
    * Ex: 51
    * @member {Number} commonVariableMostCommonConnectorId
    */
    commonVariableMostCommonConnectorId = undefined;
    /**
    * Ex: 2017-02-07 23:43:39 UTC ISO 8601 YYYY-MM-DDThh:mm:ss
    * @member {String} commonVariableUpdatedAt
    */
    commonVariableUpdatedAt = undefined;
    /**
    * When the record was first created. Use UTC ISO 8601 YYYY-MM-DDThh:mm:ss  datetime format
    * @member {String} createdAt
    */
    createdAt = undefined;
    /**
    * Ex: count
    * @member {String} unitAbbreviatedName
    */
    unitAbbreviatedName = undefined;
    /**
    * Ex: 6
    * @member {Number} unitCategoryId
    */
    unitCategoryId = undefined;
    /**
    * Ex: Miscellany
    * @member {String} unitCategoryName
    */
    unitCategoryName = undefined;
    /**
    * ID of unit to use for this variable
    * @member {Number} unitId
    */
    unitId = undefined;
    /**
    * Ex: Count
    * @member {String} unitName
    */
    unitName = undefined;
    /**
    * Ex: negative
    * @member {String} description
    */
    description = undefined;
    /**
    * Ex: Trader Joe's Bedtime Tea
    * @member {String} displayName
    */
    displayName = undefined;
    /**
    * The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.
    * @member {Number} durationOfAction
    */
    durationOfAction = undefined;
    /**
    * Ex: 168
    * @member {Number} durationOfActionInHours
    */
    durationOfActionInHours = undefined;
    /**
    * Earliest filling time
    * @member {Number} earliestFillingTime
    */
    earliestFillingTime = undefined;
    /**
    * Earliest measurement time
    * @member {Number} earliestMeasurementTime
    */
    earliestMeasurementTime = undefined;
    /**
    * Earliest source time
    * @member {Number} earliestSourceTime
    */
    earliestSourceTime = undefined;
    /**
    * error_message
    * @member {String} errorMessage
    */
    errorMessage = undefined;
    /**
    * Latest measurement start_time to be used in analysis. Use UTC ISO 8601 YYYY-MM-DDThh:mm:ss  datetime format
    * @member {String} experimentEndTime
    */
    experimentEndTime = undefined;
    /**
    * Ex: 1893477600
    * @member {Number} experimentEndTimeSeconds
    */
    experimentEndTimeSeconds = undefined;
    /**
    * Ex: 2030-01-01 06:00:00 UTC ISO 8601 YYYY-MM-DDThh:mm:ss
    * @member {String} experimentEndTimeString
    */
    experimentEndTimeString = undefined;
    /**
    * Earliest measurement start_time to be used in analysis. Use UTC ISO 8601 YYYY-MM-DDThh:mm:ss  datetime format
    * @member {String} experimentStartTime
    */
    experimentStartTime = undefined;
    /**
    * Ex: 1269307902
    * @member {Number} experimentStartTimeSeconds
    */
    experimentStartTimeSeconds = undefined;
    /**
    * Ex: 2010-03-23 01:31:42 UTC ISO 8601 YYYY-MM-DDThh:mm:ss
    * @member {String} experimentStartTimeString
    */
    experimentStartTimeString = undefined;
    /**
    * 0 -> No filling, 1 -> Use filling-value
    * @member {String} fillingType
    */
    fillingType = undefined;
    /**
    * When it comes to analysis to determine the effects of this variable, knowing when it did not occur is as important as knowing when it did occur. For example, if you are tracking a medication, it is important to know when you did not take it, but you do not have to log zero values for all the days when you haven't taken it. Hence, you can specify a filling value (typically 0) to insert whenever data is missing.
    * @member {Number} fillingValue
    */
    fillingValue = undefined;
    /**
    * Ex: ion-sad-outline
    * @member {String} iconIcon
    */
    iconIcon = undefined;
    /**
    * Ex: 95614
    * @member {Number} id
    */
    id = undefined;
    /**
    * 
    * @member {String} imageUrl
    */
    imageUrl = undefined;
    /**
    * Ex: https://google.com
    * @member {String} informationalUrl
    */
    informationalUrl = undefined;
    /**
    * Commonly defined for all users. IngredientOf variable measurements will be included in analysis of the ingredient variable.  For instance, a ingredient of the variable Lollypop could be Sugar.  This way you only have to record Lollypop consumption and we can use this data to see how sugar might be affecting you.
    * @member {Array.<module:model/Variable>} ingredientOfCommonTagVariables
    */
    ingredientOfCommonTagVariables = undefined;
    /**
    * Commonly defined for all users. IngredientOf variable measurements will be included in analysis of the ingredient variable.  For instance, a ingredient of the variable Lollypop could be Sugar.  This way you only have to record Lollypop consumption and we can use this data to see how sugar might be affecting you.
    * @member {Array.<module:model/Variable>} ingredientCommonTagVariables
    */
    ingredientCommonTagVariables = undefined;
    /**
    * User-specific IngredientOf variable measurements will be included in analysis of the ingredient variable.  For instance, a ingredient of the variable Lollypop could be Sugar.  This way you only have to record Lollypop consumption and we can use this data to see how sugar might be affecting you.
    * @member {Array.<module:model/Variable>} ingredientOfUserTagVariables
    */
    ingredientOfUserTagVariables = undefined;
    /**
    * User-specific IngredientOf variable measurements will be included in analysis of the ingredient variable.  For instance, a ingredient of the variable Lollypop could be Sugar.  This way you only have to record Lollypop consumption and we can use this data to see how sugar might be affecting you.
    * @member {Array.<module:model/Variable>} ingredientUserTagVariables
    */
    ingredientUserTagVariables = undefined;
    /**
    * Ex: value
    * @member {String} inputType
    */
    inputType = undefined;
    /**
    * 
    * @member {String} ionIcon
    */
    ionIcon = undefined;
    /**
    * Commonly defined for all users.  Joining can be used used to merge duplicate variables. For instance, if two variables called Apples (Red Delicious) and Red Delicious Apples are joined, when one of them is analyzed, the measurements for the other will be included as well.
    * @member {Array.<module:model/Variable>} joinedCommonTagVariables
    */
    joinedCommonTagVariables = undefined;
    /**
    * User-defined. Joining can be used used to merge duplicate variables. For instance, if two variables called Apples (Red Delicious) and Red Delicious Apples are joined, when one of them is analyzed, the measurements for the other will be included as well.
    * @member {Array.<module:model/Variable>} joinedUserTagVariables
    */
    joinedUserTagVariables = undefined;
    /**
    * The Variable this Variable should be joined with. If the variable is joined with some other variable then it is not shown to user in the list of variables
    * @member {Number} joinWith
    */
    joinWith = undefined;
    /**
    * Kurtosis
    * @member {Number} kurtosis
    */
    kurtosis = undefined;
    /**
    * ID of last original Unit
    * @member {Number} lastOriginalUnitId
    */
    lastOriginalUnitId = undefined;
    /**
    * Last original value which is stored
    * @member {Number} lastOriginalValue
    */
    lastOriginalValue = undefined;
    /**
    * Ex: 500
    * @member {Number} lastProcessedDailyValue
    */
    lastProcessedDailyValue = undefined;
    /**
    * When this variable or its settings were last updated UTC ISO 8601 YYYY-MM-DDThh:mm:ss
    * @member {String} lastSuccessfulUpdateTime
    */
    lastSuccessfulUpdateTime = undefined;
    /**
    * ID of last Unit
    * @member {Number} lastUnitId
    */
    lastUnitId = undefined;
    /**
    * Last Value
    * @member {Number} lastValue
    */
    lastValue = undefined;
    /**
    * Latest filling time
    * @member {Number} latestFillingTime
    */
    latestFillingTime = undefined;
    /**
    * Latest measurement time
    * @member {Number} latestMeasurementTime
    */
    latestMeasurementTime = undefined;
    /**
    * Latest source time
    * @member {Number} latestSourceTime
    */
    latestSourceTime = undefined;
    /**
    * Ex: 1501383600
    * @member {Number} latestUserMeasurementTime
    */
    latestUserMeasurementTime = undefined;
    /**
    * Latitude
    * @member {Number} latitude
    */
    latitude = undefined;
    /**
    * Location
    * @member {String} location
    */
    location = undefined;
    /**
    * Longitude
    * @member {Number} longitude
    */
    longitude = undefined;
    /**
    * Ex: 1
    * @member {Boolean} manualTracking
    */
    manualTracking = undefined;
    /**
    * The maximum allowed value for measurements. While you can record a value above this maximum, it will be excluded from the correlation analysis.
    * @member {Number} maximumAllowedValue
    */
    maximumAllowedValue = undefined;
    /**
    * Maximum recorded daily value of this variable
    * @member {Number} maximumRecordedDailyValue
    */
    maximumRecordedDailyValue = undefined;
    /**
    * Ex: 1
    * @member {Number} maximumRecordedValue
    */
    maximumRecordedValue = undefined;
    /**
    * Mean
    * @member {Number} mean
    */
    mean = undefined;
    /**
    * Number of measurements at last analysis
    * @member {Number} measurementsAtLastAnalysis
    */
    measurementsAtLastAnalysis = undefined;
    /**
    * Median
    * @member {Number} median
    */
    median = undefined;
    /**
    * The minimum allowed value for measurements. While you can record a value below this minimum, it will be excluded from the correlation analysis.
    * @member {Number} minimumAllowedValue
    */
    minimumAllowedValue = undefined;
    /**
    * Minimum recorded value of this variable
    * @member {Number} minimumRecordedValue
    */
    minimumRecordedValue = undefined;
    /**
    * Ex: 51
    * @member {Number} mostCommonConnectorId
    */
    mostCommonConnectorId = undefined;
    /**
    * Ex: 23
    * @member {Number} mostCommonOriginalUnitId
    */
    mostCommonOriginalUnitId = undefined;
    /**
    * Most common Unit ID
    * @member {Number} mostCommonUnitId
    */
    mostCommonUnitId = undefined;
    /**
    * Most common value
    * @member {Number} mostCommonValue
    */
    mostCommonValue = undefined;
    /**
    * Ex: Trader Joes Bedtime Tea / Sleepytime Tea (any Brand)
    * @member {String} name
    */
    name = undefined;
    /**
    * Ex: 1
    * @member {Number} numberOfAggregateCorrelationsAsCause
    */
    numberOfAggregateCorrelationsAsCause = undefined;
    /**
    * Ex: 310
    * @member {Number} numberOfAggregateCorrelationsAsEffect
    */
    numberOfAggregateCorrelationsAsEffect = undefined;
    /**
    * Number of changes
    * @member {Number} numberOfChanges
    */
    numberOfChanges = undefined;
    /**
    * Number of correlations for this variable
    * @member {Number} numberOfCorrelations
    */
    numberOfCorrelations = undefined;
    /**
    * Number of processed measurements
    * @member {Number} numberOfProcessedDailyMeasurements
    */
    numberOfProcessedDailyMeasurements = undefined;
    /**
    * Ex: 295
    * @member {Number} numberOfRawMeasurements
    */
    numberOfRawMeasurements = undefined;
    /**
    * Ex: 1
    * @member {Number} numberOfTrackingReminders
    */
    numberOfTrackingReminders = undefined;
    /**
    * Number of unique daily values
    * @member {Number} numberOfUniqueDailyValues
    */
    numberOfUniqueDailyValues = undefined;
    /**
    * Ex: 2
    * @member {Number} numberOfUniqueValues
    */
    numberOfUniqueValues = undefined;
    /**
    * Ex: 115
    * @member {Number} numberOfUserCorrelationsAsCause
    */
    numberOfUserCorrelationsAsCause = undefined;
    /**
    * Ex: 29014
    * @member {Number} numberOfUserCorrelationsAsEffect
    */
    numberOfUserCorrelationsAsEffect = undefined;
    /**
    * Ex: 2
    * @member {Number} numberOfUserVariables
    */
    numberOfUserVariables = undefined;
    /**
    * The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the onset delay. For example, the onset delay between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes.
    * @member {Number} onsetDelay
    */
    onsetDelay = undefined;
    /**
    * Ex: 0.5
    * @member {Number} onsetDelayInHours
    */
    onsetDelayInHours = undefined;
    /**
    * Outcome variables (those with `outcome` == 1) are variables for which a human would generally want to identify the influencing factors. These include symptoms of illness, physique, mood, cognitive performance, etc.  Generally correlation calculations are only performed on outcome variables
    * @member {Boolean} outcome
    */
    outcome = undefined;
    /**
    * Ex: 1
    * @member {Number} outcomeOfInterest
    */
    outcomeOfInterest = undefined;
    /**
    * Commonly defined for all users.  An example of a parent category variable would be Fruit when tagged with the child sub-type variables Apple.  Child variable (Apple) measurements will be included when the parent category (Fruit) is analyzed.  This allows us to see how Fruit consumption might be affecting without having to record both Fruit and Apple intake.
    * @member {Array.<module:model/Variable>} parentCommonTagVariables
    */
    parentCommonTagVariables = undefined;
    /**
    * User-defined. An example of a parent category variable would be Fruit when tagged with the child sub-type variables Apple.  Child variable (Apple) measurements will be included when the parent category (Fruit) is analyzed.  This allows us to see how Fruit consumption might be affecting without having to record both Fruit and Apple intake.
    * @member {Array.<module:model/Variable>} parentUserTagVariables
    */
    parentUserTagVariables = undefined;
    /**
    * Ex: img/variable_categories/treatments.png
    * @member {String} pngPath
    */
    pngPath = undefined;
    /**
    * Ex: https://quantimodo.quantimo.do/ionic/Modo/www/img/variable_categories/treatments.png
    * @member {String} pngUrl
    */
    pngUrl = undefined;
    /**
    * Ex: 0
    * @member {Number} predictorOfInterest
    */
    predictorOfInterest = undefined;
    /**
    * Ex: 95.4
    * @member {Number} price
    */
    price = undefined;
    /**
    * Link to associated product for purchase
    * @member {String} productUrl
    */
    productUrl = undefined;
    /**
    * Is variable public
    * @member {Number} public
    */
    public = undefined;
    /**
    * Ex: 131
    * @member {Number} rawMeasurementsAtLastAnalysis
    */
    rawMeasurementsAtLastAnalysis = undefined;
    /**
    * Ex: 1
    * @member {Number} secondMostCommonValue
    */
    secondMostCommonValue = undefined;
    /**
    * Ex: 250
    * @member {Number} secondToLastValue
    */
    secondToLastValue = undefined;
    /**
    * Ex: 1
    * @member {Boolean} shareUserMeasurements
    */
    shareUserMeasurements = undefined;
    /**
    * Skewness
    * @member {Number} skewness
    */
    skewness = undefined;
    /**
    * Comma-separated list of source names to limit variables to those sources
    * @member {String} sources
    */
    sources = undefined;
    /**
    * Standard deviation Ex: 0.46483219855434
    * @member {Number} standardDeviation
    */
    standardDeviation = undefined;
    /**
    * status
    * @member {String} status
    */
    status = undefined;
    /**
    * Based on sort filter and can be shown beneath variable name on search list
    * @member {String} subtitle
    */
    subtitle = undefined;
    /**
    * Ex: https://quantimodo.quantimo.do/ionic/Modo/www/img/variable_categories/treatments.svg
    * @member {String} svgUrl
    */
    svgUrl = undefined;
    /**
    * Ex: 6
    * @member {Number} thirdMostCommonValue
    */
    thirdMostCommonValue = undefined;
    /**
    * Ex: 250
    * @member {Number} thirdToLastValue
    */
    thirdToLastValue = undefined;
    /**
    * @member {module:model/Unit} unit
    */
    unit = undefined;
    /**
    * Universal product code or similar
    * @member {String} upc
    */
    upc = undefined;
    /**
    * updated
    * @member {Number} updated
    */
    updated = undefined;
    /**
    * When the record in the database was last updated. Use UTC ISO 8601 YYYY-MM-DDThh:mm:ss datetime format
    * @member {String} updatedAt
    */
    updatedAt = undefined;
    /**
    * Ex: 2017-07-30 14:58:26
    * @member {String} updatedTime
    */
    updatedTime = undefined;
    /**
    * User ID
    * @member {Number} userId
    */
    userId = undefined;
    /**
    * @member {Array.<module:model/Variable>} userTaggedVariables
    */
    userTaggedVariables = undefined;
    /**
    * @member {Array.<module:model/Variable>} userTagVariables
    */
    userTagVariables = undefined;
    /**
    * Ex: count
    * @member {String} userVariableUnitAbbreviatedName
    */
    userVariableUnitAbbreviatedName = undefined;
    /**
    * Ex: 6
    * @member {Number} userVariableUnitCategoryId
    */
    userVariableUnitCategoryId = undefined;
    /**
    * Ex: Miscellany
    * @member {String} userVariableUnitCategoryName
    */
    userVariableUnitCategoryName = undefined;
    /**
    * Ex: 23
    * @member {Number} userVariableUnitId
    */
    userVariableUnitId = undefined;
    /**
    * Ex: Count
    * @member {String} userVariableUnitName
    */
    userVariableUnitName = undefined;
    /**
    * Ex: -1
    * @member {Number} userVariableFillingValue
    */
    userVariableFillingValue = undefined;
    /**
    * Ex: 51
    * @member {Number} userVariableMostCommonConnectorId
    */
    userVariableMostCommonConnectorId = undefined;
    /**
    * Ex: 2017-07-30 14:58:26
    * @member {String} userVariableUpdatedAt
    */
    userVariableUpdatedAt = undefined;
    /**
    * Ex: positive or negative
    * @member {String} userVariableValence
    */
    userVariableValence = undefined;
    /**
    * Ex: 13
    * @member {Number} userVariableVariableCategoryId
    */
    userVariableVariableCategoryId = undefined;
    /**
    * Ex: Treatments
    * @member {String} userVariableVariableCategoryName
    */
    userVariableVariableCategoryName = undefined;
    /**
    * Ex: 
    * @member {String} userVariableWikipediaTitle
    */
    userVariableWikipediaTitle = undefined;
    /**
    * @member {module:model/VariableCategory} variableCategory
    */
    variableCategory = undefined;
    /**
    * @member {module:model/DataSource} dataSource
    */
    dataSource = undefined;
    /**
    * Array of Variables that are joined with this Variable
    * @member {Array.<module:model/Variable>} joinedVariables
    */
    joinedVariables = undefined;
    /**
    * Last source
    * @member {Number} lastSource
    */
    lastSource = undefined;
    /**
    * Last unit
    * @member {String} lastUnit
    */
    lastUnit = undefined;
    /**
    * Most common unit
    * @member {String} mostCommonUnit
    */
    mostCommonUnit = undefined;
    /**
    * Ex: positive
    * @member {String} valence
    */
    valence = undefined;
    /**
    * Ex: 6
    * @member {Number} variableCategoryId
    */
    variableCategoryId = undefined;
    /**
    * Ex: https://maxcdn.icons8.com/Color/PNG/96/Household/sleeping_in_bed-96.png
    * @member {String} variableCategoryImageUrl
    */
    variableCategoryImageUrl = undefined;
    /**
    * Variable category like Mood, Sleep, Physical Activity, Treatment, Symptom, etc.
    * @member {String} variableCategoryName
    */
    variableCategoryName = undefined;
    /**
    * Ex: -1
    * @member {Number} variableFillingValue
    */
    variableFillingValue = undefined;
    /**
    * Ex: 96380
    * @member {Number} variableId
    */
    variableId = undefined;
    /**
    * Ex: Sleep Duration
    * @member {String} variableName
    */
    variableName = undefined;
    /**
    * Ex: 115947037.40816
    * @member {Number} variance
    */
    variance = undefined;
    /**
    * Ex: 
    * @member {String} wikipediaTitle
    */
    wikipediaTitle = undefined;








}


