/**
 * quantimodo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.728
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ChartStyle'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ChartStyle'));
  } else {
    // Browser globals (root is window)
    if (!root.Quantimodo) {
      root.Quantimodo = {};
    }
    root.Quantimodo.Loading = factory(root.Quantimodo.ApiClient, root.Quantimodo.ChartStyle);
  }
}(this, function(ApiClient, ChartStyle) {
  'use strict';




  /**
   * The Loading model module.
   * @module model/Loading
   * @version 5.8.824
   */

  /**
   * Constructs a new <code>Loading</code>.
   * @alias module:model/Loading
   * @class
   * @param style {module:model/ChartStyle} 
   * @param hideDuration {Number} Example: 10
   * @param showDuration {Number} Example: 10
   */
  var exports = function(style, hideDuration, showDuration) {
    var _this = this;

    _this['style'] = style;
    _this['hideDuration'] = hideDuration;
    _this['showDuration'] = showDuration;
  };

  /**
   * Constructs a <code>Loading</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Loading} obj Optional instance to populate.
   * @return {module:model/Loading} The populated <code>Loading</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('style')) {
        obj['style'] = ChartStyle.constructFromObject(data['style']);
      }
      if (data.hasOwnProperty('hideDuration')) {
        obj['hideDuration'] = ApiClient.convertToType(data['hideDuration'], 'Number');
      }
      if (data.hasOwnProperty('showDuration')) {
        obj['showDuration'] = ApiClient.convertToType(data['showDuration'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ChartStyle} style
   */
  exports.prototype['style'] = undefined;
  /**
   * Example: 10
   * @member {Number} hideDuration
   */
  exports.prototype['hideDuration'] = undefined;
  /**
   * Example: 10
   * @member {Number} showDuration
   */
  exports.prototype['showDuration'] = undefined;



  return exports;
}));


