/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.100414
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Marker', 'model/State', 'model/Tooltip'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Marker'), require('./State'), require('./Tooltip'));
  } else {
    // Browser globals (root is window)
    if (!root.Quantimodo) {
      root.Quantimodo = {};
    }
    root.Quantimodo.Scatter = factory(root.Quantimodo.ApiClient, root.Quantimodo.Marker, root.Quantimodo.State, root.Quantimodo.Tooltip);
  }
}(this, function(ApiClient, Marker, State, Tooltip) {
  'use strict';




  /**
   * The Scatter model module.
   * @module model/Scatter
   * @version 5.8.1114
   */

  /**
   * Constructs a new <code>Scatter</code>.
   * @alias module:model/Scatter
   * @class
   * @param marker {module:model/Marker} 
   * @param states {module:model/State} 
   * @param tooltip {module:model/Tooltip} 
   */
  var exports = function(marker, states, tooltip) {
    var _this = this;

    _this['marker'] = marker;
    _this['states'] = states;
    _this['tooltip'] = tooltip;
  };

  /**
   * Constructs a <code>Scatter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Scatter} obj Optional instance to populate.
   * @return {module:model/Scatter} The populated <code>Scatter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('marker')) {
        obj['marker'] = Marker.constructFromObject(data['marker']);
      }
      if (data.hasOwnProperty('states')) {
        obj['states'] = State.constructFromObject(data['states']);
      }
      if (data.hasOwnProperty('tooltip')) {
        obj['tooltip'] = Tooltip.constructFromObject(data['tooltip']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Marker} marker
   */
  exports.prototype['marker'] = undefined;
  /**
   * @member {module:model/State} states
   */
  exports.prototype['states'] = undefined;
  /**
   * @member {module:model/Tooltip} tooltip
   */
  exports.prototype['tooltip'] = undefined;



  return exports;
}));


