/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.100414
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Title'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Title'));
  } else {
    // Browser globals (root is window)
    if (!root.Quantimodo) {
      root.Quantimodo = {};
    }
    root.Quantimodo.YAxi = factory(root.Quantimodo.ApiClient, root.Quantimodo.Title);
  }
}(this, function(ApiClient, Title) {
  'use strict';




  /**
   * The YAxi model module.
   * @module model/YAxi
   * @version 5.8.1109
   */

  /**
   * Constructs a new <code>YAxi</code>.
   * @alias module:model/YAxi
   * @class
   * @param lineWidth {Number} Example: 1
   * @param max {Number} Example: 372.68
   * @param min {Number} Example: -2.68
   * @param opposite {Boolean} Example: true
   * @param title {module:model/Title} 
   */
  var exports = function(lineWidth, max, min, opposite, title) {
    var _this = this;

    _this['lineWidth'] = lineWidth;
    _this['max'] = max;
    _this['min'] = min;
    _this['opposite'] = opposite;
    _this['title'] = title;
  };

  /**
   * Constructs a <code>YAxi</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/YAxi} obj Optional instance to populate.
   * @return {module:model/YAxi} The populated <code>YAxi</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('lineWidth')) {
        obj['lineWidth'] = ApiClient.convertToType(data['lineWidth'], 'Number');
      }
      if (data.hasOwnProperty('max')) {
        obj['max'] = ApiClient.convertToType(data['max'], 'Number');
      }
      if (data.hasOwnProperty('min')) {
        obj['min'] = ApiClient.convertToType(data['min'], 'Number');
      }
      if (data.hasOwnProperty('opposite')) {
        obj['opposite'] = ApiClient.convertToType(data['opposite'], 'Boolean');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = Title.constructFromObject(data['title']);
      }
    }
    return obj;
  }

  /**
   * Example: 1
   * @member {Number} lineWidth
   */
  exports.prototype['lineWidth'] = undefined;
  /**
   * Example: 372.68
   * @member {Number} max
   */
  exports.prototype['max'] = undefined;
  /**
   * Example: -2.68
   * @member {Number} min
   */
  exports.prototype['min'] = undefined;
  /**
   * Example: true
   * @member {Boolean} opposite
   */
  exports.prototype['opposite'] = undefined;
  /**
   * @member {module:model/Title} title
   */
  exports.prototype['title'] = undefined;



  return exports;
}));


