/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.112511
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Quantimodo);
  }
}(this, function(expect, Quantimodo) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Quantimodo.Button();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Button', function() {
    it('should create an instance of Button', function() {
      // uncomment below and update the code to test Button
      //var instane = new Quantimodo.Button();
      //expect(instance).to.be.a(Quantimodo.Button);
    });

    it('should have the property action (base name: "action")', function() {
      // uncomment below and update the code to test the property action
      //var instane = new Quantimodo.Button();
      //expect(instance).to.be();
    });

    it('should have the property additionalInformation (base name: "additionalInformation")', function() {
      // uncomment below and update the code to test the property additionalInformation
      //var instane = new Quantimodo.Button();
      //expect(instance).to.be();
    });

    it('should have the property color (base name: "color")', function() {
      // uncomment below and update the code to test the property color
      //var instane = new Quantimodo.Button();
      //expect(instance).to.be();
    });

    it('should have the property confirmationText (base name: "confirmationText")', function() {
      // uncomment below and update the code to test the property confirmationText
      //var instane = new Quantimodo.Button();
      //expect(instance).to.be();
    });

    it('should have the property functionName (base name: "functionName")', function() {
      // uncomment below and update the code to test the property functionName
      //var instane = new Quantimodo.Button();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Quantimodo.Button();
      //expect(instance).to.be();
    });

    it('should have the property image (base name: "image")', function() {
      // uncomment below and update the code to test the property image
      //var instane = new Quantimodo.Button();
      //expect(instance).to.be();
    });

    it('should have the property ionIcon (base name: "ionIcon")', function() {
      // uncomment below and update the code to test the property ionIcon
      //var instane = new Quantimodo.Button();
      //expect(instance).to.be();
    });

    it('should have the property link (base name: "link")', function() {
      // uncomment below and update the code to test the property link
      //var instane = new Quantimodo.Button();
      //expect(instance).to.be();
    });

    it('should have the property successToastText (base name: "successToastText")', function() {
      // uncomment below and update the code to test the property successToastText
      //var instane = new Quantimodo.Button();
      //expect(instance).to.be();
    });

    it('should have the property successAlertTitle (base name: "successAlertTitle")', function() {
      // uncomment below and update the code to test the property successAlertTitle
      //var instane = new Quantimodo.Button();
      //expect(instance).to.be();
    });

    it('should have the property successAlertBody (base name: "successAlertBody")', function() {
      // uncomment below and update the code to test the property successAlertBody
      //var instane = new Quantimodo.Button();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instane = new Quantimodo.Button();
      //expect(instance).to.be();
    });

    it('should have the property tooltip (base name: "tooltip")', function() {
      // uncomment below and update the code to test the property tooltip
      //var instane = new Quantimodo.Button();
      //expect(instance).to.be();
    });

  });

}));
